### ISSUE TITLE
bug in hicupCountInteractions.py

### ISSUE THREAD

**Issue by xflicsu** [BauerLab/ngsane#48]
Hello ngsane designers,
I have install ngsane to deal with HiC-seq datasets.
There may be an bug in hicupCountInteractions.py
##########################
python /usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py --verbose --genomeFragmentFile=/usr/packages/ngsane/0.5.0.3/smokebox/common/hicup/Digest_hg19_Ncol_none.txt --outputDir=/usr/packages/ngsane/0.5.0.3/smokebox/HiC/hicup/ /usr/packages/ngsane/0.5.0.3/smokebox/HiC/hicup/GMall_Ncol_uniques.bam

###########################################################################
Traceback (most recent call last):
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 415, in <module>
    main()
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 141, in main
    process()
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 407, in process
    [ fragmentList, fragmentPairs ] = countReadsPerFragment(intersect_tree)
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 316, in countReadsPerFragment
    readpair = findNextReadPair(samiter)
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 242, in findNextReadPair
    readpair=[getNext(samiter), getNext(samiter)]
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 231, in getNext
    return Read(iterator.next())
  File "/usr/packages/ngsane/0.5.0.3//tools/hicupCountInteractions.py", line 24, in __init__
    if (read==""):
TypeError: Argument 'other' has incorrect type (expected pysam.calignmentfile.AlignedSegment, got str)

##################################
So, how to fix this bug?
Thanks for your attention!

**Comment by Gurado** [comment]
Hi, 

could you specify which HiCuP version you are using and also check whether the generated bam file (/usr/packages/ngsane/0.5.0.3/smokebox/HiC/hicup/GMall_Ncol_uniques.bam) matches the following stats:
```bash
>samtools flagstat GMall_Ncol.asd.bam
34186 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
34186 + 0 mapped (100.00%:-nan%)
34186 + 0 paired in sequencing
17093 + 0 read1
17093 + 0 read2
34186 + 0 properly paired (100.00%:-nan%)
34186 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by xflicsu** [comment]
Hello, I find the error result from "samtools sort" command. My system have installed a previous version.   When I change to 1.1, it works well. Thanks!
